### PR TITLE
About intro

### PR DESCRIPTION
**Pull request by emilyPhee**
- Add About Intro component
- Add Instructor Introduction component
  - use Sanity Block content with @portabletext/react npm package
  - set language based on the preferred language

### CODE REVIEW

**Review by emilyPhee — COMMENTED** [review]
reviewed

**Comment by emilyPhee** [comment]
[About Page: Intro](https://trello.com/c/wne1KiXM/41-about-page-intro)

**Comment by emilyPhee** [comment]
[About Page: Intro](https://trello.com/c/wne1KiXM/41-about-page-intro)

**Review by anthopark — APPROVED** [review]
LGTM!

**Pull request merged**
